
project_id = "ugozxdxoyhajqigcuykc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "https://ugozxdxoyhajqigcuykc.supabase.co"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
inactivity_timeout = 900
site_url = "https://ugozxdxoyhajqigcuykc.supabase.co"
enable_signup = true
enable_confirmations = false
enable_manual_linking = false

[db]
enabled = true
port = 54322
major_version = 15

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[edge_functions]
enabled = true
port = 54321

[functions.categorize-product]
verify_jwt = true
