// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugozxdxoyhajqigcuykc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnb3p4ZHhveWhhanFpZ2N1eWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODk4NTQsImV4cCI6MjA1OTg2NTg1NH0._LWqQMPs05t9Sle5uJEeAiAn-oh4oqKc-PFKjUxVeuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);